FROM python:3.10

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD ["streamlit", "run", "streamlit_ui/app.py", "--server.port=8501", "--server.enableCORS=false"]
