FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY streamlit_ui/ /app/streamlit_ui/

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_ui/app.py", "--server.port=8501", "--server.enableCORS=false"]

