apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: streamlit-liquidity-sandbox
build:
  artifacts:
    - image: streamlit-liquidity-app
      context: .
      docker:
        dockerfile: Dockerfile.streamlit
  local:
    push: false
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
portForward:
  - resourceType: service
    resourceName: streamlit-service
    port: 8501
    localPort: 8501
