apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: liquidity-sandbox
build:
  artifacts:
    - image: streamlit-app
      context: .
      docker:
        dockerfile: Dockerfile.streamlit
deploy:
  kubectl:
    manifests:
      - k8s/streamlit-app.yaml
